---
- name: Enable Internet Services
  hosts: servera
  remote_user: roshan
  become: yes
  become_method: sudo

  tasks: 
  - name: Install Packages
    ansible.builtin.dnf:
         name: 
           - firewalld
           - httpd
           - mariadb-server
           - php
           - php-mysqlnd
         state: latest
           
  - name: StartFirewalld Service
    ansible.builtin.service:
         name: firewalld
         state: started
         enabled: yes

  - name: Enable HTTP service
    ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled

  - name: Start HTTPD  Service
    ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

  - name: Start MariaDB Service
    ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
  
  - name: Copy File from Hos
    ansible.builtin.copy: 
        src: index.php
        dest: /var/www/html
        mode: '0644'
