---
- name: Basic Playbook
  hosts: ec2 

  tasks: 
   - name: Remove Apache
     yum:
        name: httpd
        state: absent 

   - name: Install Apache
     yum: 
         name: httpd
         state: present
    
   - name: Add New User 
     user: 
        name: roshan
        home: /home/roshan
        