---
- name: Basic Playbook
  hosts: ec2 

  tasks: 
   - name: Remove Apache
     yum:
        name: httpd
        state: absent 

   - name: Install Apache
     yum: 
         name: httpd
         state: present
    
   - name: Add New User 
     user: 
        name: roshan
        home: /home/roshan

   - name: Echo New User Details
     shell: 
        cmd: id roshan > /tmp/id.txt  && cat /tmp/id.txt
