---
- name: Playbook which will mount a volume 
  hosts: ec2 


  tasks: 
  - name: Creation  Partion  #Parted Module documentation https://docs.ansible.com/ansible/latest/collections/community/general/parted_module.html
    parted: 
      device: /dev/xvdf
      fs_type: xfs # Can use ext4 as well for the file system
      label: gpt # Partion Table Default is msdos which MBR 
      number: 1 # Partion Number 
      part_start: 0% # Partstar
      part_end: 100% # Which means take full disk
      part_type: primary #Default
      state: present # Default is info In order to creation partion set this to present

  - name: Create a Directory 
    file: 
      path: /opt/ansiblemount/
      state: directory 
      owner: ec2-user
      group: ec2-user 
      mode: '0755'

  - name: Create Filesystem once disk is partioned # Module Documentation https://docs.ansible.com/ansible/latest/collections/community/general/filesystem_module.html
    filesystem: 
          dev: /dev/xvdf1
          fstype: xfs


  - name: Mount partioned volume to location using mount module # https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html
    mount: 
      path: /opt/ansiblemount # Directory on the remote host 
      src: /dev/xvdf1 #Mount parition
      fstype: xfs
      state: mounted
