---
# tasks file for roles/apache
- name: Install Apache 
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Enable APache Service 
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes 

- name: Enable Firewalld Service 
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes 

- name: Enable HTTP service on firewall
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Deploy Template 
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache

